language: go

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"
  - "1.15"
  - "1.16"
  - "1.17"

before_script:
  # only do tests in latest version
  - go version | grep go1.11 && export $DO_LINT="true" || true
  - if [ "$DO_LINT" = "true" ]; then go get -u golang.org/x/lint/golint; fi
  - if [ "$DO_LINT" = "true" ]; then go get github.com/mattn/goveralls; fi

script:
  - test -z $(gofmt -s -l ./*.go)
  - go test -v -covermode=count -coverprofile=profile.cov ./...
  - if [ "$DO_LINT" = "true" ]; then go vet ./...; fi
  - if [ "$DO_LINT" = "true" ]; then goveralls -coverprofile=profile.cov -service=travis-ci -repotoken $COVERALLS_TOKEN || true ; fi
    
